document.write('    <nav class="navbar navbar-default" role="navigation">')
document.write('      <div class="navbar-header">')
document.write('<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">')
document.write('<span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>')
document.write('       </button><a class="navbar-brand" href="#">Code The Change</a></div>')
document.write('<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">')
document.write('        <ul class="nav navbar-nav"> <li class="active"><a href="login.html">Home</a></li>')
document.write('          <li><a href="about.html">About</a></li><li><a href="#developers">Developers</a></li></ul>')
document.write('      </div><!-- /.navbar-collapse --></nav>')   
